# Generated by Django 4.2.4 on 2023-08-12 10:08

import schedule.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(blank=True, max_length=25, null=True)),
                ('age', models.IntegerField()),
                ('short_description', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(default='media/default.png', upload_to=schedule.models.profile_photos)),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
            },
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('duration', models.TimeField()),
                ('weekdays', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=12)),
                ('end_time', models.TimeField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.coach')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.sporttype')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='sport_coaching',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.sporttype'),
        ),
    ]
