# Generated by Django 4.2.4 on 2023-08-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_traininginfo_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='slug_field',
            field=models.SlugField(default=''),
        ),
    ]
