# Generated by Django 4.2.4 on 2023-08-22 06:26

from django.db import migrations, models
import django.db.models.deletion
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_traininginfo_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='profile_image',
        ),
        migrations.CreateModel(
            name='ProfileImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=schedule.models.profile_photos)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='schedule.coach')),
            ],
        ),
    ]
