# Generated by Django 4.2.4 on 2023-08-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_coach_profile_image_profileimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileImages',
            new_name='ProfileImage',
        ),
        migrations.AlterModelOptions(
            name='profileimage',
            options={'verbose_name': 'Profile image', 'verbose_name_plural': 'Profile images'},
        ),
        migrations.AlterModelOptions(
            name='traininginfo',
            options={'verbose_name_plural': 'TrainingsInfo'},
        ),
    ]
