# Generated by Django 4.2.4 on 2023-08-22 08:36

from django.db import migrations, models
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_stupid_naming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='slug_field',
            field=models.SlugField(default=''),
        ),
    ]
