# Generated by Django 4.2.4 on 2023-08-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_coach_slug_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='short_description',
            new_name='description',
        ),
    ]
