# Generated by Django 4.2.4 on 2023-08-23 15:02

from django.db import migrations, models
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='profile_image',
            field=models.ImageField(default='media/default.png', upload_to=schedule.models.profile_photos),
            preserve_default=False,
        ),
    ]
