# Generated by Django 4.2.4 on 2023-08-26 08:41

from django.db import migrations, models
import django.db.models.manager
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_coach_profile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sporttype',
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='sporttype',
            name='slug_field',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='profile_image',
            field=models.ImageField(upload_to=schedule.models.profile_photo),
        ),
    ]
