# Generated by Django 4.2.4 on 2023-08-29 05:03

from django.db import migrations, models
import django.db.models.deletion
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_sporttype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporttype',
            name='main_image',
            field=models.ImageField(default='sport_type/no_image_available.svg', upload_to=schedule.models.sport_images),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='profile_image',
            field=models.ImageField(default='coaches/default/', upload_to=schedule.models.profile_photo),
        ),
        migrations.CreateModel(
            name='SportImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=schedule.models.sport_images)),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='schedule.sporttype')),
            ],
        ),
    ]
