# Generated by Django 4.2.4 on 2023-09-04 14:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_sporttype_main_image_alter_coach_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coach',
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
