# Generated by Django 4.2.4 on 2023-09-04 18:54

from django.db import migrations, models
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_coach_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='slug_field',
            field=models.SlugField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sporttype',
            name='slug_field',
            field=models.SlugField(blank=True, default='', max_length=20),
        ),
    ]
