# Generated by Django 4.2.4 on 2023-09-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_alter_coach_slug_field_alter_sporttype_slug_field'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coach',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sporttype',
            managers=[
            ],
        ),
    ]
